### ISSUE TITLE
Scores unmerged PRs

### ISSUE THREAD

**Issue by mjcrouse** [brandongk-ubco/gitstats#89] opened 2020-10-13 17:17 UTC
If a PR is opened and closed without merging, it is still used in gitstats, even though other group members may have not had a chance to commit/comment/review or if it was opened in error

**Comment by brandongk-ubco** [comment] 2020-10-13 17:43
Hi @mjcrouse thanks for reporting this issue.  This was changed by design in the last release, with the intention of giving credit for work even if it doesn't make it into the final codebase.  Are you encountering a case where results are being drastically affected by such PRs?

@bohuie

**Comment by mjcrouse** [comment] 2020-10-13 17:53
Hrm interesting decision. We had a group member start a PR with two .ai files which would have added 28000 lines of code. We agreed it was better to host on our google drive so it was closed without merging. Our changes scores this week are now 100, 0.25 and 0.41.

**Comment by brandongk-ubco** [comment] 2020-10-13 17:59
Ok, so in that worst case of ~0.25, you should be seeing a final score ~2.25% less for that person, correct?  And this should be only this week.

I'll talk to Dr. Hui and see what she wants to do.  Unfortunately, I think there are cases to be made for both counting and not counting, so it's not obvious to me how to handle this use case.

**Comment by mjcrouse** [comment] 2020-10-13 18:06
Assuming team score changes give individual marks of 100% to members with 66.66+ effort with a 1.5 team score we should be fine this week. I think that math is off, although I'm not perfectly clear on it. Changes are worth 20% of individual effort (3/15) so 0.25/100 is effectively 0 so a 20% reduction in grade (in the 1.0 team score case). Correct me if I'm wrong

**Comment by brandongk-ubco** [comment] 2020-10-17 01:16
@mjcrouse We have a proposed path forward on this, specifically to address the fact that, in rare cases, PRs can have a very large numbers of lines changed.  This is described in #94 so I am closing this issue in favour of that one.

There are use cases on both sides of scoring closed PRs, and it doesn't make sense to go back-and-forth based on a single example.  We are going to stick with counting closed but unmerged PRs for now.

Thanks for bringing this up!

**Closed by brandongk-ubco** 2020-10-17 01:16 UTC

**Comment by mjcrouse** [comment] 2020-10-17 02:42
Sounds good. Thanks for the prompt initial responses and the feedback.

**Comment by merelister** [comment] 2020-10-18 01:42
@brandongk-ubco We've noticed that approving a PR for a code review does not count as participation in a PR according to gitstats - would it perhaps be possible to use this feature to decide whether to count LoC? For example, if a PR is not approved then it is not counted, whether it is merged or not.
