### ISSUE TITLE
Issues created outside of given date range are not counted

### ISSUE THREAD

**Issue by merelister** [brandongk-ubco/gitstats#100] opened 2020-10-19 22:25 UTC
Suggested solution: do not consider the issues’ date of creation when determining which issues are “counted” towards the teams effort for the given date range.

Reason: this does not allow for the common Agile workflow where you pull tickets from the backlog at the beginning of each sprint (its tough to schedule a sprint if you don’t have an idea of the effort it will take because you don’t have all your tickets with the acceptance criteria)

cc @rachellegelden @Parsa-Rajabi

**Comment by brandongk-ubco** [comment] 2020-10-20 01:08
@merelister @rachellegelden @Parsa-Rajabi

What you describe it is certainly the intention.  The code for determining if an issue should be included is here:

https://github.com/brandongk-ubco/gitstats/blob/807280c6cea14d8271896be9f86adbd08a781375/gitstats/GithubAPIRepository.py#L134

There was a time where updated_at was used, but that was corrected in v1.0.4: https://github.com/brandongk-ubco/gitstats/commit/f6f40e3dcd8322adbce8ffd4b100258ed5677aa4

Does this resolve this issue?

**Comment by brandongk-ubco** [comment] 2020-10-20 01:19
As an aside, I believe you are using the backlog properly in your example.

**Comment by brandongk-ubco** [comment] 2020-10-26 21:12
@rachellegelden @Parsa-Rajabi @merelister - I have not heard any more on this issue, so I am closing it as stale.  Please reopen if it persists.

**Comment by brandongk-ubco** [comment] 2021-01-28 21:37
I tried re-creating this with issue #120 and it looks to work as expected.  The issue was created at 1:15 PM Kelowna Time, and closed at 1:34 PM.  When I run the report from 1:30 to 2:00 PM I see:

=============
Issues Closed
=============
   label  completed
0  chore          1

When I run the report from 1:00 PM to 2:00 PM I see the same.

**Comment by rachellegelden** [comment] 2021-01-28 21:41
> I tried re-creating this with issue #120 and it looks to work as expected. The issue was created at 1:15 PM Kelowna Time, and closed at 1:34 PM. When I run the report from 1:30 to 2:00 PM I see:
> 
> ```
> =============
> Issues Closed
> =============
>    label  completed
> 0  chore          1
> ```
> 
> When I run the report from 1:00 PM to 2:00 PM I see the same.

Would it help if we gave you temporary access to our repo that we run gitstats on every week? You could then reproduce the issue there to help figure out what is going on

**Comment by brandongk-ubco** [comment] 2021-01-28 21:47
Probably.  If you are OK to give me an API key and repo name, and a list of the issues you are expecting to see, I can try directly on your repo.  brandon.grahamknight@ubc.ca if you want to e-mail it to me, then I can let you know when I am done with the key so you can remove it.

**Comment by brandongk-ubco** [comment] 2021-01-28 21:47
@rachellegelden - Oh, and the dates for the report you are trying to run.  Thanks!

**Comment by brandongk-ubco** [comment] 2021-01-28 21:48
Or you can just add me to the repo if you want and I can use a key from my account, your choice.

**Comment by mjcrouse** [comment] 2021-01-28 22:24
This was an issue for us again this week (in @merelister group ). 

  for issue in self.repository.get_issues(state="closed",
                                                sort="closed",
                                                direction="desc"):
            if issue.closed_at > end:
                continue
            if issue.closed_at < start:
                break

It looks like this breaks as soon as it sees an issue that was closed outside of the specified time frame.

![image](https://user-images.githubusercontent.com/46467432/106206040-4cf29900-6174-11eb-87cc-b175b3b26558.png)

Here is our list of closed issues. The ones with checkmarks and X's were closed this week but only the checkmarks were counted.

**Comment by JadenBalogh** [comment] 2021-01-28 22:31
Can confirm, our group also encountered this issue this week. Any issues created earlier than the 1-week time frame were not counted, despite being closed and properly tagged.

**Comment by brandongk-ubco** [comment] 2021-01-28 23:38
@mjcrouse @JadenBalogh @rachellegelden I think this is now fixed... the GitHub API had some strangeness I had not accounted for, but using a better test case I was able to debug.  It should go out in the next release.

**Closed** 2021-01-29 03:58 UTC

**Comment by brandongk-ubco** [comment] 2021-01-29 04:06
Released in v1.1.0
