### ISSUE TITLE
Data do not match with repo

### ISSUE THREAD

**Issue by yyht6300a** [brandongk-ubco/gitstats#123] opened 2021-03-03 18:39 UTC
We are in group Minecraft-C.
We used the latest version and the correct time range, but the output does not match with what we have in repo.  It's like the account yyht6300 did 23 commits from 10th February to 3rd March, but it returned 10. Many of the data is incorrect.

**Comment by brandongk-ubco** [comment] 2021-03-04 05:19
@yyht6300a - You shouldn't put your API key in a public forum like this.  You should change it immediately.

The number of commits / changes / comments are calculated from PRs which were closed during the report window.  It is not calculated from the total number applied to the repo.  In short, the work is credited when it is completed.  Do the numbers match up with that understanding?

**Comment by Ansper11** [comment] 2021-03-05 00:29
@brandongk-ubco  Hi Brandon

this is our report:
period: 2021-02-10 19:00:00 to 2021-03-03 18:00:00
0    Eloise Espel          27         665           14             17
1  Nicholas McGee          25       13684           25              19
2        caincdiy          11         401           33              23
3       yyht6300a          10         169           20              20

The problem is the number of commits, changes, and comments in the report are not match the number in our GitHub for period: 2021-02-10 19:00:00 to 2021-03-03 18:00:00.

For example, account caincdiy doesn't make 33 comments during the period: 2021-02-10 19:00:00 to 2021-03-03 18:00:00
also, the contribution should be less than 23. The problems are the same for commits and comments, we haven't made as many changes as the number shown in the report.

However, I run another gitstats for this week (1 week) and it works now, I don't know if the problem above is because the period is too long(3 weeks).

**Comment by brandongk-ubco** [comment] 2021-03-05 18:07
Hi @caincdiy - When you are collecting the values you expect, are you starting with which PRs were completed during that time period?  All of the calculations from comments / commits / changes are calculated from PRs which were completed (merged / closed) during the time period.

**Comment by Ansper11** [comment] 2021-03-05 18:32
Yes, I think the time is correct.

**Comment by brandongk-ubco** [comment] 2021-03-05 18:41
@caincdiy I am not questioning the timeframe, I am questioning how you counted the number of commits / comments / changes.  When you are looking at the # of commits (for example) you can't just count how many commits a user pushed to the repo during the timeframe.  You need to look at which PRs were merged / closed during that timeframe, then the number of commits a user applied to those PRs.  Can you confirm that you started with PRs and then went from there?  I want to rule out that this issue is a simple misunderstanding on how the calculation is performed.

**Comment by brandongk-ubco** [comment] 2021-03-05 18:43
@caincdiy - If you look [here](https://github.com/brandongk-ubco/gitstats/blob/develop/docs/technical/evaluation.md), you can see the Individual contribution is measured through:

> participation in completed pull requests
> number of comments on completed pull requests
> number of commits on completed pull requests
> number of changes on completed pull requests

Note that **on completed pull requests** - this is the part I want to confirm.

**Comment by Ansper11** [comment] 2021-03-05 19:05
Yes, but we only have 14 PRs during that timeframe, so how did 17,19,23,20 on contribution come from

**Comment by brandongk-ubco** [comment] 2021-03-05 19:14
Does 14 include both closed (without merging) and merged PRs?

**Comment by Ansper11** [comment] 2021-03-05 19:17
Yes

**Comment by brandongk-ubco** [comment] 2021-03-05 19:22
In the Individual Contributions section, there should be a column for PR.  Are there only 14 unique numbers in that list?

```
========================
Individual Contributions
========================
                    user  **pr**  commits  additions  deletions  changes  \
0  Brandon Graham-Knight  **52**        1         97        102      199   
1  Brandon Graham-Knight  **53**        6        116        121      237   
2  Brandon Graham-Knight  **54**       10        318        330      648   
3  Brandon Graham-Knight  **59**        2         82         47      129   

   comments  contributed  
0         0         True  
1         0         True  
2         1         True  
3         0         True  
```

**Comment by brandongk-ubco** [comment] 2021-03-05 19:43
@caincdiy - I just saw that the output I quoted above was suppressed in a previous version for brevity.  You can install a branch which puts it back in so that you can verify:

https://github.com/brandongk-ubco/gitstats/pull/124

You need to run: `pip install --force-reinstall git+https://github.com/brandongk-ubco/gitstats@addproutput`

Then run it again.  If you are running jupyter make sure to shut down your notebook / lab session and reimport before running again so that it picks up the new version.  You should see **alpha** as the gitstats version.

**Comment by Ansper11** [comment] 2021-03-05 19:52
I get an error: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'INSTALLER'
Consider using the `--user` option or check the permissions.

But it works for this week, maybe we can just keep using the current version for the remaining 4 weeks

**Comment by brandongk-ubco** [comment] 2021-03-05 19:56
I am almost positive that the root of this issue is PRs being included which you did not expect to be included.  The error you posted above is probably because of how you have Python setup, which I can't really help debug.  The user flag may fix it, but I am not sure.

I'll ask Dr. Hui about re-adding this output as a normal release, which should probably done to help with these types of issues in the future.

**Comment by Ansper11** [comment] 2021-03-05 19:59
Ok thanks a lot for your time

**Closed as completed** 2021-03-08 21:16 UTC
